### ISSUE TITLE
[Feature Request] Custom hook for translation

### ISSUE THREAD

**Issue by IniZio** [oursky/react-messageformat#12]
Currently we can use `<FormattedMessage id="" />` to easily translate in layout elements, but it does not cater some scenario well such as:

- Layout that requires translation result in string e.g. Helmet meta attributes
- Translations that are not used in layout e.g.:
   ```jsx
    function PostEditor() {
      const { addToast } = useToast();
      addToast(message);
    }
   ```

Think a hook version will help in these cases?

**Comment by cychiuae** [comment]
https://github.com/oursky/react-messageformat/blob/303a4d441b25a3fb4e26f6ae54c48cd7f30a82cb/index.d.ts#L58 ?

**Comment by louischan-oursky** [comment]
A hook will not be very helpful because calling a hook has some restrictions, such as you must unconditionally call it, and you cannot call a hook in a loop. You can just use `useContext` to get `renderToString` to imperatively get translated message, as  suggested by @cychiuae

**Comment by IniZio** [comment]
Sure will close related PR 🙏
